#!/bin/bash

names=("zero" "one" "two" "three" "four" "five" "six" "seven" "eight" "nine")


nameindeces=("${!names[@]}")

echo "${namer[@]}"

for i in "${nameindeces[@]}"; do
	if [[ $i -eq 2 ]]; then
		for j in "${nameindeces[@]}"; do
			$(sudo useradd "elec${names[i]}${names[j]}" -p  "elec${names[i]}${names[j]}password")
			echo  "user elec${names[i]}${names[j]} created"
			if [[ $j -eq 0 ]]; then
				break;
			fi
		done
		break;
	fi

	for j in "${nameindeces[@]}"; do
		$(sudo useradd "elec${names[i]}${names[j]}" -p  "elec${names[i]}${names[j]}password")
		echo  "user elec${names[i]}${names[j]} created"
	done
done
