#!/bin/bash

names=("zero" "one" "two" "three" "four" "five" "six" "seven" "eight" "nine")

arg1=$(($1/10))
arg2=$(($1%10))


nameindeces=("${!names[@]}")

for i in "${nameindeces[@]}"; do
	if [[ $i -eq $arg1 ]]; then
		for j in "${nameindeces[@]}"; do
			$(sudo useradd  -p$(openssl passwd -1 "elec${names[i]}${names[j]}password") -m "elec${names[i]}${names[j]}")
			echo  "user elec${names[i]}${names[j]} created with password elec${names[i]}${names[j]}password "
			if [[ $j -eq $arg2 ]]; then
				break;
			fi
		done
		break;
	fi

	for j in "${nameindeces[@]}"; do
		$(sudo useradd  -p$(openssl passwd -1 "elec${names[i]}${names[j]}password")  "elec${names[i]}${names[j]}")
		echo  "user elec${names[i]}${names[j]} created with password elec${names[i]}${names[j]}password "
	done
done
